name: Release Feature Marketplace
on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-release:
    runs-on: ubuntu-latest
    name: Build Release
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Perform Marketplace Release
        uses: cloudcoach-actions/marketplace-release@v1
